### ISSUE TITLE
Freeze on Safari (iPhone, iPad, Macbook)

### ISSUE THREAD

**Issue by deepspacerace** [mars-2026/mars26_com#4]
> Attempting to zoom in or out on my iPhone 12 freezes the site. I’m using Safari.

https://news.ycombinator.com/reply?id=26966831&goto=item%3Fid%3D26965583%2326966831

**Comment by vassudanagunta** [comment]
Freezes on Safari / M1 Macbook Air too. 

I can do one or two pans, and then it locks up.

Might want to change the title of this issue.

**Comment by deepspacerace** [comment]
Another case on iPad: (from hackernews)

> Similar problem here, a single action works (pan or zoom), then the map is frozen and I can’t do anything. I’m using the latest Safari on an iPad Pro.

**Comment by deepspacerace** [comment]
@vassudanagunta Should be fixed now

**Comment by vassudanagunta** [comment]
yup. thanks. cool!
